-- DemoAlert 初始化（S02 模板深化）
-- MySQL 8 / utf8mb4；可重复执行：先删后建（仅演示库）

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS sys_org (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  org_id BIGINT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_username (username),
  KEY idx_user_org (org_id),
  CONSTRAINT fk_user_org FOREIGN KEY (org_id) REFERENCES sys_org (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_role_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE RESTRICT,
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES sys_role (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alert (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  title VARCHAR(256) NOT NULL,
  severity VARCHAR(8) NOT NULL,
  status VARCHAR(16) NOT NULL,
  owner_id BIGINT NULL,
  org_id BIGINT NOT NULL,
  source VARCHAR(32) NULL,
  close_reason VARCHAR(32) NULL,
  remark VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_alert_code (code),
  KEY idx_alert_org_status (org_id, status),
  KEY idx_alert_owner (owner_id),
  CONSTRAINT fk_alert_org FOREIGN KEY (org_id) REFERENCES sys_org (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alert_event (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  alert_id BIGINT NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  payload JSON NULL,
  occurred_at DATETIME NOT NULL,
  operator_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_event_alert (alert_id, occurred_at),
  CONSTRAINT fk_event_alert FOREIGN KEY (alert_id) REFERENCES alert (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO sys_role (code, name)
SELECT * FROM (SELECT 'admin' AS code, '系统管理员' AS name) t
WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE code = 'admin');
INSERT INTO sys_role (code, name)
SELECT * FROM (SELECT 'operator', '值班操作员') t
WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE code = 'operator');
INSERT INTO sys_role (code, name)
SELECT * FROM (SELECT 'viewer', '只读观察者') t
WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE code = 'viewer');
